### ISSUE TITLE
tested on Windows?

### ISSUE THREAD

**Issue by brucemackenzie** [Crafity/crafity-imageinfo#2]
npm info install crafity-filesystem@0.1.6
npm info postinstall crafity-filesystem@0.1.6
npm verb about to build d:\work\super-deduper\node_modules\crafity-imageinfo
npm ERR! crafity-jstest@0.1.13 install: `scripts/npm-install.sh`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the crafity-jstest@0.1.13 install script.
npm ERR! This is most likely a problem with the crafity-jstest package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     scripts/npm-install.sh
npm ERR! You can get their info via:
npm ERR!     npm owner ls crafity-jstest
npm ERR! There is likely additional logging output above.

npm ERR! System Windows_NT 6.2.9200
npm ERR! command "c:\\Program Files (x86)\\nodejs\\node.exe" "c:\\Program Files (x86)\\nodejs\\node_modules\\npm\\bin\\n
pm-cli.js" "install" "--save" "crafity-imageinfo" "--verbose"
npm ERR! cwd d:\work\super-deduper
npm ERR! node -v v0.10.33
npm ERR! npm -v 1.4.28
npm ERR! code ELIFECYCLE
npm verb exit [ 1, true ]
npm verb node_modules\crafity-imageinfo\node_modules\crafity-jstest unbuild
npm info preuninstall crafity-jstest@0.1.13
npm info uninstall crafity-jstest@0.1.13

**Comment by briemens** [comment]
This module has not been tested on windows, but what I can see is that there is an issue with a dependency crafity-jstest. This dependency has been updated recently.

Please check again.

**Comment by brucemackenzie** [comment]
I'll try that. Thanks.
